version: '3.8'

services:
  api: 
    container_name: api
    build: 
      context: ../api
      dockerfile: Api.Dockerfile
    env_file:
      - ./api/.env
    ports:
      - '4000:4000'
    volumes:
      - ../api:/app
    depends_on:
      - database
    command: 
      - /bin/sh 
      - -c
      - |
        mix deps.get
        mix ecto.migrate
        mix phx.server
       
  database: 
    container_name: database
    image: postgres:alpine
    env_file:
      - ./database/.env
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
